buildscript {
    repositories {
        google()
        mavenCentral()  // ✅ 최신 Gradle 사용을 위해 `jcenter()` 대신 `mavenCentral()` 사용
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.3.0'  // ✅ 최신 버전 사용
    }

}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.layout.buildDirectory
}
